apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    name: ump-app
  name: ump-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: ump-webapp
---
apiVersion: v1
kind: ReplicationController
metadata:
  namespace: default
  labels:
    name: ump-webapp
  name: ump-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: ump-webapp
    spec:
      containers:
      - image: $NEXUS_SERVER:8082/admin/ump-deploy
        name: ump-app
        ports:
        - name: ump-app
          containerPort: 8080
        env:
        - name: WEBAPP_NAME
          value: ${UMP_WEBAPP_FILE_NAME}
        - name: BACKEND_NAME
          value: ${UMP_BACKEND_FILE_NAME}
        command: ["/bin/sh","-c"]
        args: ["./home/ubuntu/ump-conf/entrypoint.sh"]
